---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I don’t love you as if you were a rose of salt, topaz,  
or arrow of carnations that propagate fire:  
I love you as one loves certain obscure things,  
secretly, between the shadow and the soul.  

I love you as the plant that doesn’t bloom but carries  
the light of those flowers, hidden, within itself,  
and thanks to your love the tight aroma that arose  
from the earth lives dimly in my body.  

I love you without knowing how, or when, or from where,  
I love you directly without problems or pride:  
I love you like this because I don’t know any other way   to love,  
except in this form in which I am not nor are you,  
so close that your hand upon my chest is mine,  
so close that your eyes close with my dreams.  
